"""The GitHub Pages entry point is generated, so it must not drift."""

import subprocess
import sys
from pathlib import Path

import pytest

from scripts import build_pages

ROOT = Path(__file__).resolve().parent.parent


def test_index_exists():
    assert build_pages.TARGET.exists(), "run python scripts/build_pages.py"


def test_index_is_in_sync_with_its_source():
    # The artifact source is the one that gets edited; this catches a commit
    # that changes it and forgets to regenerate the page Pages serves.
    assert build_pages.TARGET.read_text(encoding="utf-8") == build_pages.render()


def test_check_mode_passes_when_in_sync():
    result = subprocess.run(
        [sys.executable, "scripts/build_pages.py", "--check"],
        cwd=ROOT, capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr


@pytest.fixture(scope="module")
def page():
    return build_pages.TARGET.read_text(encoding="utf-8")


class TestGeneratedDocument:
    def test_it_is_a_complete_document(self, page):
        # The artifact source has no skeleton -- served raw it would be quirks
        # mode with no charset and no viewport.
        assert page.startswith("<!doctype html>")
        for tag in ("<html lang=", "<head>", "<body>", "</html>"):
            assert tag in page

    def test_it_declares_charset_and_viewport(self, page):
        assert '<meta charset="utf-8">' in page
        assert "viewport-fit=cover" in page

    def test_it_carries_link_preview_metadata(self, page):
        assert 'property="og:title"' in page
        assert 'name="description"' in page

    def test_it_says_it_is_generated(self, page):
        assert "Generated by scripts/build_pages.py" in page

    def test_the_app_itself_is_present(self, page):
        assert "<title>Thirsttrap</title>" in page
        assert "grammarGenerate" in page
        assert "thirsttrap.profile.v1" in page

    def test_it_declares_no_claude_capability(self, page):
        # Pages serves this to anyone; it must not try to bill a viewer.
        assert "claude.use" not in page
        assert "sample" not in page


def test_nojekyll_is_present():
    # Without it Pages runs Jekyll, which skips paths beginning with _ and .
    assert (ROOT / ".nojekyll").exists()
