#!/usr/bin/env python3
"""Generate the GitHub Pages entry point from the artifact source.

`web/thirsttrap.html` is written for the Artifact publisher, which wraps the
file in its own document skeleton -- so the source deliberately has no
<!doctype>, <html>, <head> or <body>. Served raw by Pages that renders in
quirks mode with no charset and no viewport, which looks broken on a phone.

So Pages gets a generated file rather than a second copy: one source of truth,
and `test_pages.py` fails if `index.html` drifts out of date.

    python scripts/build_pages.py            # write index.html
    python scripts/build_pages.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "web" / "thirsttrap.html"
TARGET = ROOT / "index.html"

REPO = "https://github.com/ike49285-alt/Bipbip"
SUMMARY = (
    "Draft posts for X and rank them by an eight-component scorer that learns "
    "from what you keep. Runs entirely in your browser."
)

# Mirrors what the Artifact viewer provides, so the page behaves the same in
# both places: safe-area padding, a sane reset, and an explicit viewport.
SKELETON = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Thirsttrap">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="theme-color" content="#16131a">
<meta name="description" content="{summary}">
<meta property="og:title" content="Thirsttrap">
<meta property="og:description" content="{summary}">
<meta property="og:type" content="website">
<link rel="canonical" href="{repo}">
<style>
  :root {{
    color-scheme: light dark;
    padding-top: env(safe-area-inset-top, 0px);
    padding-bottom: env(safe-area-inset-bottom, 0px);
  }}
  body {{ margin: 0; font: 14px system-ui, sans-serif; background: #faf9f8; }}
  img {{ max-width: 100%; }}
  [hidden] {{ display: none !important; }}
</style>
</head>
<body>
<!-- Generated by scripts/build_pages.py from web/thirsttrap.html. Do not edit. -->
{content}
</body>
</html>
"""


def render() -> str:
    return SKELETON.format(
        content=SOURCE.read_text(encoding="utf-8").strip(),
        summary=SUMMARY,
        repo=REPO,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="exit 1 if index.html is missing or out of date, and write nothing",
    )
    args = parser.parse_args(argv)

    if not SOURCE.exists():
        print(f"error: {SOURCE} is missing", file=sys.stderr)
        return 2

    expected = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if args.check:
        if current == expected:
            print(f"{TARGET.name} is up to date")
            return 0
        print(
            f"error: {TARGET.name} is stale -- run `python scripts/build_pages.py`",
            file=sys.stderr,
        )
        return 1

    if current == expected:
        print(f"{TARGET.name} already up to date")
        return 0

    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {TARGET.name} ({len(expected):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
